# A Docker Compose file to setup a Data Virtualization environment

services:

  dremio:
    image: dremio/dremio-oss
    container_name: dremio
    ports:  
      - 9047:9047 
      - 31010:31010 
      - 45678:45678
      - 32010:32010
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    volumes:
      - dremio:/opt/dremio/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  postgres:
    image: postgres:15.3-alpine3.18
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./resources/db.sh:/docker-entrypoint-initdb.d/init-database.sh
      - ./resources:/resources
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes: 
  dremio:
  postgres:
    